# Generated by Django 4.2.11 on 2024-04-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresdb', '0002_category_item_tag_delete_book_item_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='category',
        ),
    ]
