# Generated by Django 4.2.11 on 2024-04-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresdb', '0003_rename_name_tag_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='category',
            new_name='name',
        ),
    ]
