# Generated by Django 4.2.11 on 2024-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresdb', '0004_rename_name_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.CharField(max_length=50),
        ),
    ]
