# Generated by Django 4.2.11 on 2024-04-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresdb', '0005_alter_item_available_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
